In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [3]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import load_digits
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score

In [4]:
from sklearn.model_selection import KFold
kf=KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [5]:
# StratifiedKFold is better then the KFold when you separting out your folds 
# it will divide each of the classification categories in a uniform way.
from sklearn.model_selection import StratifiedKFold
folds=StratifiedKFold(n_splits=3)
folds

StratifiedKFold(n_splits=3, random_state=None, shuffle=False)

In [6]:
digits=load_digits()

In [7]:
x_train,x_test,y_train,y_test=train_test_split(digits.data,digits.target,test_size=0.2,random_state=235)

In [8]:
lr=LogisticRegression()
lr.fit(x_train,y_train)
lr.score(x_test,y_test)

C:\Users\Umair IT Solution\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9722222222222222

In [9]:
svm=SVC()
svm.fit(x_train,y_train)
svm.score(x_test,y_test)

0.9833333333333333

In [10]:
rfc=RandomForestClassifier(n_estimators=70)
rfc.fit(x_train,y_train)
rfc.score(x_test,y_test)

0.975

In [11]:
# Showing the  kfold working.kf stands for kfold which is going to do the 3 splits.
for train_index,test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [12]:
# function to get score
def get_score(model,x_train,x_test,y_train,y_test):
    model.fit(x_train,y_train)
    return model.score(x_test,y_test)

In [13]:
# SVM score by function
get_score(SVC(),x_train,x_test,y_train,y_test)

0.9833333333333333

In [14]:
# Logistic Regression score by function
get_score(LogisticRegression(),x_train,x_test,y_train,y_test)

C:\Users\Umair IT Solution\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9722222222222222

In [15]:
# Random forest score by function
get_score(RandomForestClassifier(n_estimators=70),x_train,x_test,y_train,y_test)

0.975

In [23]:
# This code show how kfold works.But in real life we don't use this code 
# instead. we use crossvalscore which is inside the sklearn library.
scores_l=[]
scores_svm=[]
scores_rf=[]

for train_index,test_index in kf.split(digits.data):
    x_train,x_test,y_train,y_test=digits.data[train_index],digits.data[test_index], \
                                  digits.target[train_index],digits.target[test_index]
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=70),x_train,x_test,y_train,y_test))
    scores_svm.append(get_score(SVC(),x_train,x_test,y_train,y_test))
    scores_l.append(get_score(LogisticRegression(),x_train,x_test,y_train,y_test))

C:\Users\Umair IT Solution\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Umair IT Solution\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    htt

In [24]:
scores_l
 

[0.9232053422370617, 0.9415692821368948, 0.9148580968280468]

In [25]:

scores_svm


[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]

In [26]:
scores_rf

[0.9265442404006677, 0.9582637729549248, 0.9282136894824707]

In [28]:
# First argument is your classifier then x then y
cross_val_score(LogisticRegression(),digits.data,digits.target,cv=3)

C:\Users\Umair IT Solution\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Umair IT Solution\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    htt

array([0.92153589, 0.94156928, 0.91652755])

In [29]:
cross_val_score(SVC(),digits.data,digits.target,cv=3)

array([0.96494157, 0.97996661, 0.96494157])

In [30]:
cross_val_score(RandomForestClassifier(n_estimators=70),digits.data,digits.target,cv=3)

array([0.92821369, 0.94991653, 0.93489149])